import Image from 'next/image';
import Link from 'next/link';
import Navigation from '../components/Navigation';
import { ProjectStatus, TechnologyTags } from '../components/ProjectUI';
import { education, experience, moreProjects, projects, site, skills } from '../data/portfolio';

const external = { target: '_blank', rel: 'noopener noreferrer' } as const;

function Heading({ number, children, intro }: { number: string; children: React.ReactNode; intro?: string }) {
  return <div className="section-heading"><p>{number}</p><h2>{children}</h2>{intro && <span>{intro}</span>}</div>;
}

export default function Home() {
  return <><Navigation /><main id="top">
    <section className="hero" aria-labelledby="hero-title"><div className="container hero-grid">
      <div className="hero-copy"><p className="eyebrow"><span aria-hidden="true" /> {site.location} · Open to technical opportunities</p><h1 id="hero-title">{site.name}</h1><p className="hero-role">{site.headline}</p><p className="hero-summary">Cybersecurity student with prior computer science coursework building software, Linux environments, automation workflows, and hands-on systems projects. Interested in technology from application software through operating systems, networking, and hardware.</p><div className="hero-actions"><a className="button primary" href="#projects">View Projects</a><a className="button secondary" href="#about">About Me</a></div><div className="social-links" aria-label="Professional links"><a href={site.github} {...external}>GitHub ↗</a><a href={site.linkedin} {...external}>LinkedIn ↗</a><a href="/resume.pdf" {...external}>Resume ↗</a></div></div>
      <div className="terminal" aria-label="Technical focus presented as terminal output"><div className="terminal-bar"><span /><span /><span /><code>aarav@portfolio:~</code></div><div className="terminal-body"><p><b>aarav@portfolio</b>:~$ whoami</p><output>student · software / systems builder</output><p><b>aarav@portfolio</b>:~$ cat focus.txt</p><output>Linux · Software · Systems · Cybersecurity</output><p><b>aarav@portfolio</b>:~$ git status --short</p><output><em>M</em> building, learning, troubleshooting</output><i className="cursor" aria-hidden="true" /></div></div>
    </div></section>

    <section id="about" className="section about"><div className="container about-grid"><Heading number="01 — About">I like figuring out how things actually work.</Heading><div className="about-copy"><p>I am studying cybersecurity after prior computer science coursework, with hands-on Windows and Linux experience spanning command-line work, Arch Linux desktop configuration, PC building, and software and hardware troubleshooting.</p><p>When something breaks, I start from the symptom and work down through the layers: the process or service involved, its logs, permissions, the network, and finally the hardware. Once I find the cause, I write the fix into a script or a doc so it doesn’t have to be solved twice. The Hyprland installer grew that way, one hardware-specific fix at a time.</p><p>Outside of systems work I build software products end to end, from a study platform for aviation-maintenance students to an AI-assisted resume tool, because shipping something real is the fastest way I know to learn.</p><dl className="quick-facts"><div><dt>Based in</dt><dd>{site.location}</dd></div><div><dt>Studying</dt><dd>Cybersecurity &amp; Information Assurance, ARC</dd></div><div><dt>Open to</dt><dd>IT support, systems, security &amp; software roles</dd></div><div><dt>Currently building</dt><dd><Link href={projects.pathway.caseStudy}>Pathway</Link></dd></div></dl></div></div></section>

    <section id="projects" className="section project-section"><div className="container"><Heading number="02 — Projects" intro="Practical work across Linux environments, software products, and deployed applications.">Selected work</Heading>
      <article className="featured-project"><div className="featured-copy"><p className="project-kicker">{projects.hyprland.category}</p><h3>{projects.hyprland.name}</h3><h4>{projects.hyprland.subtitle}</h4><p>A reusable, Bash-based installation workflow for deploying a personalized Hyprland environment on Arch Linux. It includes Intel, AMD, and NVIDIA configuration paths and has been deployed on desktop hardware and an HP OmniBook laptop.</p><ul className="proof-list"><li><b>01</b><span>Hardware-aware configuration and package management</span></li><li><b>02</b><span>systemd and journalctl setup and troubleshooting</span></li><li><b>03</b><span>Git-tracked configuration, setup guidance, and documentation</span></li></ul><TechnologyTags tags={projects.hyprland.tags} /><div className="project-actions"><Link className="button light" href={projects.hyprland.caseStudy}>View Case Study</Link><a href={projects.hyprland.repository} {...external}>Repository ↗</a></div></div><div className="project-visual"><Image src="/hyprlandproof.webp" width={1920} height={804} sizes="(max-width: 850px) calc(100vw - 64px), 52vw" alt="Configured Hyprland desktop with application launcher and system panels on Arch Linux" priority /><Image className="terminal-shot" src="/hyprlandproofterminal.webp" width={1920} height={804} sizes="(max-width: 850px) calc(100vw - 64px), 30vw" alt="Terminal windows open in the configured Aarav Hyprland desktop environment" /></div></article>
      <div className="additional-heading"><div><p className="project-kicker">Product engineering</p><h3>Software Products</h3></div><span>One evolving · one deployed</span></div>
      <div className="project-cards">
        <article className="product-card"><div className="product-card-top"><p>{projects.pathway.category}</p><ProjectStatus status={projects.pathway.status} /></div><div className="product-diagram" aria-label="Pathway guided workflow"><span>Resume</span><i>→</i><span>Job</span><i>→</i><span>Analyze</span><i>→</i><span>Tailor</span></div><h3>{projects.pathway.name}</h3><p>{projects.pathway.description}</p><TechnologyTags tags={projects.pathway.tags} /><div className="product-card-actions"><Link href={projects.pathway.caseStudy}>View Case Study <span>→</span></Link></div></article>
        <article className="product-card"><div className="product-card-top"><p>{projects.wrenchAI.category}</p><ProjectStatus status={projects.wrenchAI.status} /></div><div className="product-card-visual"><Image src="/wrenchai-dashboard.webp" width={1600} height={1071} sizes="(max-width: 600px) calc(100vw - 64px), (max-width: 1200px) 45vw, 520px" alt="WrenchAI dashboard showing study navigation, performance tabs, and General, Airframe, and Powerplant practice sections" /></div><h3>{projects.wrenchAI.name}</h3><p>{projects.wrenchAI.description}</p><TechnologyTags tags={projects.wrenchAI.tags} /><div className="product-card-actions"><Link href={projects.wrenchAI.caseStudy}>View Case Study <span>→</span></Link><a href={projects.wrenchAI.liveSite} {...external}>View Live Site <span>↗</span></a></div></article>
      </div>
      <div className="additional-heading"><div><p className="project-kicker">Breadth</p><h3>More projects</h3></div><span>{moreProjects.length} repositories · problem, decisions, status</span></div>
      <div className="more-projects">{moreProjects.map((item) => <article className="mini-project" key={item.name}>
        <div className="product-card-top"><p>{item.category}</p><ProjectStatus status={item.status} /></div>
        <h3>{item.name}</h3><p>{item.problem}</p>
        <p className="mini-label">Key decisions</p><ul>{item.decisions.map((decision) => <li key={decision}>{decision}</li>)}</ul>
        <p className="mini-label">Where it stands</p><p>{item.outcome}</p>
        <TechnologyTags tags={item.tags} />
        <div className="product-card-actions">{item.caseStudy && <Link href={item.caseStudy}>Case Study <span>→</span></Link>}<a href={item.repository} {...external}>Repository <span>↗</span></a></div>
      </article>)}</div>
    </div></section>

    <section id="skills" className="section skills-section"><div className="container"><Heading number="03 — Skills" intro="Each group says where I used it and links to the work or coursework behind it.">Technical toolkit</Heading><div className="skills-grid">{skills.map((group) => <article className="skill-group" key={group.title}><div className="skill-top"><span aria-hidden="true">{group.symbol}</span><h3>{group.title}</h3></div><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul><p className="skill-used">{group.usedIn}</p><p className="skill-evidence"><span>Evidence</span>{group.evidence.map((link) => link.href.startsWith('http') ? <a key={link.href} href={link.href} {...external}>{link.label} ↗</a> : <Link key={link.href} href={link.href}>{link.label} →</Link>)}</p></article>)}</div></div></section>
    <section id="experience" className="section"><div className="container split-section"><Heading number="04 — Experience">Reliability in structured, high-volume work.</Heading><div className="experience-list">{experience.map((job) => <article className="timeline" key={job.company}><div className="timeline-marker" aria-hidden="true" /><div className="timeline-head"><div><p>{job.company} · {job.location}</p><h3>{job.title}</h3></div><time>{job.dates}</time></div><p>{job.summary}</p></article>)}</div></div></section>
    <section id="education" className="section education-section"><div className="container split-section"><Heading number="05 — Education">Cybersecurity study built on a computer science foundation.</Heading><div className="education-list">{education.map((item, index) => <article className={index ? 'prior' : ''} key={item.school}><span>{item.dates}{'location' in item ? ` · ${item.location}` : ''}</span><h3>{item.school}</h3><p>{item.program}</p>{index === 0 && <p className="education-note">Upcoming study includes networking, systems administration, routing and wireless, and network security fundamentals.</p>}</article>)}</div></div></section>
    <section id="contact" className="contact-section"><div className="container contact-grid"><div><p className="eyebrow">{site.location} · Let’s connect</p><h2>Interested in building and learning with a technical team.</h2><p>I’m open to software, IT and systems, cybersecurity, Linux and infrastructure, technical support, and other early-career technology opportunities.</p></div><div className="contact-links"><a href={`mailto:${site.email}`}><span>Email</span><b>Start a conversation →</b></a><a href={site.linkedin} {...external}><span>LinkedIn</span><b>Connect ↗</b></a><a href={site.github} {...external}><span>GitHub</span><b>View projects ↗</b></a><a href="/resume.pdf" {...external}><span>Resume</span><b>Open PDF ↗</b></a></div></div></section>
  </main><footer><div className="container"><b>AJ<span>.</span></b><p>© {new Date().getFullYear()} Aarav Jit. Built with Next.js and deployed through GitHub Pages.</p><a href="#top">Back to top ↑</a></div></footer></>;
}
