import Image from 'next/image';
import Link from 'next/link';
import Navigation from '../../../components/Navigation';

const repo = 'https://github.com/AaravJit/aarav-hyprland';
const external = { target: '_blank', rel: 'noopener noreferrer' } as const;

export default function HyprlandCaseStudy() {
  return <><Navigation /><main className="case-study">
    <header className="case-hero"><div className="container"><Link href="/#projects" className="back-link">← Back to projects</Link><p className="project-kicker">System configuration case study</p><h1>Aarav Hyprland</h1><p>A reusable Arch Linux and Hyprland configuration and installation repository designed to support multiple hardware configurations.</p><div className="case-meta"><span>Arch Linux</span><span>Hyprland</span><span>Bash</span><span>Git &amp; GitHub</span></div></div></header>
    <section className="case-section"><div className="container case-two-col"><div><p className="case-label">01 — Overview</p><h2>A repeatable desktop environment</h2></div><div className="case-prose"><p>The project packages a personally configured Hyprland environment into reusable configuration files and a Bash-based installation workflow. It supports separate Intel, AMD, and NVIDIA configuration paths and has been deployed on both desktop hardware and an HP OmniBook laptop.</p><h3>The practical problem</h3><ul><li>Reproducing the same environment across systems</li><li>Managing hardware-specific configuration paths</li><li>Avoiding repetitive manual setup</li><li>Documenting a repeatable installation workflow</li></ul></div></div></section>
    <section className="case-section dark"><div className="container"><p className="case-label">02 — Screenshots</p><h2>Desktop and terminal views</h2><figure><Image src="/hyprlandproof.png" width={3440} height={1440} sizes="100vw" alt="Aarav Hyprland desktop environment running on Arch Linux" priority /><figcaption>Configured Hyprland desktop environment on Arch Linux.</figcaption></figure><figure><Image src="/hyprlandproofterminal.png" width={3440} height={1440} sizes="100vw" alt="Terminal view of the Aarav Hyprland Arch Linux environment" /><figcaption>Terminal view showing the working Arch Linux environment.</figcaption></figure></div></section>
    <section className="case-section"><div className="container case-two-col"><div><p className="case-label">03 — Technical details</p><h2>Environment and highlights</h2></div><div className="case-prose"><h3>Environment</h3><p>Arch Linux · Hyprland · Bash · Git and GitHub · Intel, AMD, and NVIDIA configuration paths · Desktop deployment · HP OmniBook laptop deployment</p><h3>Technical highlights</h3><ul><li>Bash-based installation workflow</li><li>Reusable, Git-tracked configuration files</li><li>Hardware-specific configuration paths</li><li>Arch Linux package management and Hyprland configuration</li><li>Cross-device deployment and installation documentation</li></ul><h3>Challenges and troubleshooting</h3><p>The verified project scope required managing hardware-specific configuration and reusable paths across desktop and laptop deployments. Package handling, installation troubleshooting, and display differences are treated as configuration concerns rather than a claim of universal device support.</p></div></div></section>
    <section className="case-section tint"><div className="container case-two-col"><div><p className="case-label">04 — Installation flow</p><h2>Documented, hardware-aware setup</h2></div><div className="case-prose"><ol><li>Obtain the configuration repository from GitHub.</li><li>Review the repository documentation and select the relevant hardware configuration path.</li><li>Follow the documented Bash-based installation workflow.</li><li>Validate the Hyprland environment on the target system and troubleshoot device-specific differences.</li></ol><p>This summary intentionally omits unverified shell commands. Consult the repository README for the current, complete instructions.</p><a className="button primary" href={`${repo}#readme`} {...external}>Read installation documentation ↗</a></div></div></section>
    <section className="case-section"><div className="container case-two-col"><div><p className="case-label">05 — Looking ahead</p><h2>Improvements and lessons</h2></div><div className="case-prose"><h3>Future improvements</h3><ul><li>Stronger validation and improved error handling</li><li>Broader device testing</li><li>Expanded installation and troubleshooting documentation</li><li>Automated checks where they fit the workflow</li></ul><h3>Lessons learned</h3><p>The project builds practical experience in troubleshooting, Linux system configuration, Bash scripting, Git workflows, cross-device deployment, and writing documentation that makes setup repeatable.</p><a className="text-link" href={repo} {...external}>View repository ↗</a></div></div></section>
  </main><footer><div className="container"><b>AJ<span>.</span></b><p>Aarav Hyprland case study</p><Link href="/">Home</Link></div></footer></>;
}
